name: golang test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Build go binary
        run: make server

      - name: Setup test services with docker-compose
        run: make test